Jenkinsfile
docker/Dockerfile
package.json

The most important changes which could have side effects are the update from node-16 to node-18 (inside the docker image) and the changed version inside the package.json

Reworked the jenkins pipeline

---

.vscode/settings.json
apps/site/components/overview/student.tsx
libs/data-access/api/src/lib/auth.ts
libs/data-access/api/src/lib/trpc/routers/me.router.ts
libs/data-access/database/prisma/schema.prisma
libs/data-access/database/src/lib/demo/demo.ts
libs/data-access/database/src/lib/demo/java-example.ts
libs/data-access/database/src/lib/math/math-example.ts
libs/data-access/database/src/lib/psychology/psychology-example.ts
libs/data-access/database/src/lib/seed-functions.ts
libs/data-access/database/src/lib/seed.ts
libs/feature/admin/src/lib/author/update-author.spec.ts
libs/util/testing/src/lib/database-helpers.ts

Fixes unique usernames (use RZ-account instead of full names).

Fix unique usernames

---

libs/feature/admin/src/lib/author/edit-author-dialog.tsx

fix(edit-author-dialog): adds scrollbar for small devices #60

---

libs/data-access/database/prisma/migrations/20231103151054_skills_pathfinder/migration.sql

feat(migration): migrates the skill repositorie #78

---

libs/data-access/database/src/lib/demo/demo.ts
libs/data-access/database/src/lib/seed-functions.ts
libs/feature/teaching/src/lib/course/course-content-editor/dialogs/edit-lesson-dialog.tsx
libs/ui/forms/src/lib/textfield.tsx
libs/util/common/src/index.ts
libs/util/common/src/lib/umlaut-slugify.test.ts
libs/util/common/src/lib/umlaut-slugify.ts
libs/util/testing/src/lib/example-data-generator.ts

fix(slug): use correct umlaut escaping

---

libs/data-access/database/src/lib/demo/demo.ts
libs/data-access/database/src/lib/demo/license.ts
libs/data-access/database/src/lib/seed-functions.ts

fix(seed): Fix foreign key exception in seeding process for licenses

---

.dockerignore
.eslintignore
Dockerfile
Jenkinsfile
apps/site-e2e/src/e2e/course-editor.cy.ts
apps/site-e2e/src/e2e/lesson-editor.cy.ts
apps/site/next.config.js
apps/site/pages/dashboard/courseOverview.tsx
libs/data-access/database/src/lib/prisma.ts
nx.json

feat(nx-cloud): setup nx cloud workspace 
This commit set up Nx Cloud for your Nx workspace enabling distributed caching
and GitHub integration for fast CI and improved Developer Experience.
You can access your Nx Cloud workspace by going to 
https://cloud.nx.app/orgs/66cc011084a793b218a77837/workspaces/66d5cea1d4db452f4b0cfdcd
**Note:** This commit attempts to maintain formatting of the nx.json, however you may need to correct formatting by running an nx format command and committing the changes.

feat(nx-cloud): setup nx workspace

---

libs/data-access/api/src/lib/trpc/routers/settings.router.ts
libs/util/types/src/lib/event-log.ts

log events when user disables the learning diary #214

---

libs/data-access/api/src/lib/trpc/routers/learning-diary.router.ts

Makes use of a transaction for DiaryPage creation to ensure data integrity.

Use of a Transaction for the Creation of Learning Diary Pages

---

apps/site/pages/teaching/lessons/create.tsx
apps/site/pages/teaching/lessons/edit/[lessonId].tsx
libs/feature/question-types/src/lib/question-types/arrange/form.tsx

Fixes drag-and-drop functionality for the arrange task.
Updates the redirect after saving from the deprecated /overview page to /dashboard/author

Lesson Editor Arrange Task fix 

---

libs/data-access/database/prisma/deploy-migrations.ts
libs/data-access/database/prisma/migrations/20241121132634_learning_diary_descriptions/data-migration.ts
libs/data-access/database/src/lib/learning-diary/learning-strategies.tsx
libs/data-access/database/src/lib/seed-functions.ts

Seeds Learning Strategies & Techniques
Tested on empty database & cloned production data.

Seeding strategy data

---

libs/feature/teaching/src/lib/lesson/forms/lesson-info.tsx
libs/feature/teaching/src/lib/lesson/forms/quiz-editor.tsx
package-lock.json

Adds the lost text field for selfRegulatedQuestions

---

libs/feature/teaching/src/lib/lesson/lesson-editor.tsx
libs/ui/common/src/lib/button/icon-only-button.tsx
libs/ui/forms/src/lib/markdown-editor.tsx

+ small refactor to avoid code repetition

fix(teaching): Avoid save & close when editing markdown

---

apps/site/__tests__/quiz.spec.tsx
libs/feature/admin/src/lib/search-user-dialog.spec.tsx
libs/feature/diary/src/lib/enable-diary-dialog.spec.tsx
libs/feature/diary/src/lib/goals/status.spec.tsx
libs/feature/settings/src/lib/onboarding/first-login-dialog.spec.tsx
libs/feature/settings/src/lib/settings-form/settings-form.spec.tsx
package-lock.json
package.json

Switches fireEvent to userEvent

---

libs/feature/teaching/src/lib/lesson/forms/lesson-content.spec.tsx
libs/feature/teaching/src/lib/lesson/forms/lesson-content.tsx
libs/feature/teaching/src/lib/lesson/forms/lesson-info.tsx
libs/ui/common/src/index.ts
libs/ui/common/src/lib/use-first-render.ts
libs/ui/forms/src/lib/markdown-editor.tsx
libs/util/types/src/lib/lesson-content.ts

Texteingabefeld für Aktivierungsfrage fehlt im Editor für Lerneinheiten

---

libs/data-access/api/src/lib/trpc/routers/event-log.router.ts
libs/data-access/database/src/lib/access/events/user-eventlog.spec.ts
libs/data-access/database/src/lib/access/events/user-eventlog.ts
libs/util/types/src/lib/event-log.ts

Disable log entries when setting is not set

---

libs/data-access/database/src/lib/demo/demo.ts
libs/data-access/database/src/lib/demo/skill-based-modelling.ts
libs/feature/teaching/src/lib/skills/skill-lib.spec.ts
package-lock.json
package.json

* Updated Library
* Example Seed
* Test that documents path algorithm: libs/feature/teaching/src/lib/skills/skill-lib.spec.ts

Skill-Lib Usage

---

libs/ui/layouts/src/lib/redirect-to-login.ts
libs/ui/layouts/src/redirect-to-login.spec.ts

filtered redirect so correct url is used

fix(redirect-to-login): fixed issue with "//selflearn" in url

---

libs/feature/teaching/src/lib/course/course-content-editor/dialogs/lesson-editor-dialog.tsx

Open in seperate Editor during Course creation leads to 404

---

libs/feature/question-types/src/lib/question-type-registry.tsx
libs/feature/question-types/src/lib/question-types/language-tree/TreeEditor.tsx
libs/feature/question-types/src/lib/question-types/language-tree/component.tsx
libs/feature/question-types/src/lib/question-types/language-tree/evaluate.ts
libs/feature/question-types/src/lib/question-types/language-tree/form.tsx
libs/feature/question-types/src/lib/question-types/language-tree/schema.ts
libs/feature/question-types/src/lib/question-types/language-tree/tree-parser.ts
libs/feature/question-types/src/lib/question-types/language-tree/tree-visualization.tsx

feat(sprachbaum): added support for multiple answers

---

libs/feature/question-types/src/lib/question-types/arrange/form.tsx

In the Categories in the ordnen quiz-editor there was no option to rename the categories. I added this functionality.

feat(quiz-editor) Categories can now be renamed

---

libs/ui/forms/src/lib/markdown-editor.tsx
libs/util/markdown/src/lib/markdown.ts
libs/util/markdown/src/lib/rehype-image-attributes.ts

feat(markdown): add size menu for images

---

apps/site/pages/_app.tsx
libs/feature/diary/src/lib/goals/learning-goals.tsx
libs/feature/teaching/src/lib/course/course-info-form.tsx
libs/ui/layouts/src/lib/search-bar.spec.tsx
libs/ui/layouts/src/lib/search-bar.tsx
package-lock.json
package.json

- Adds `nextI18NextConfig` to `_app.tsx`
- Replaces wrong `react-i18next` imports with correct `next-i18next`
- Removes `react-i18next`dependency from project

fix: Removal of NO_I18NEXT_INSTANCE errors during build

---

libs/feature/question-types/src/lib/question-types/multiple-choice/component.tsx

- When justified: Surrounding border of question did not span the whole width
- When not justified: Background overlapped with border
- When showing results: Background did not span whole width

feat(question-types): Display issue fix of multiple choice questions
